// Generated by 'unplugin-auto-import'
export {}
declare global {
  const assign: typeof import('lodash-es')['assign']
  const axios: typeof import('axios')['default']
  const forEach: typeof import('lodash-es')['forEach']
  const isPlainObject: typeof import('lodash-es')['isPlainObject']
  const merge: typeof import('lodash-es')['merge']
  const remove: typeof import('lodash-es')['remove']
  const throttle: typeof import('lodash-es')['throttle']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    readonly assign: UnwrapRef<typeof import('lodash-es')['assign']>
    readonly axios: UnwrapRef<typeof import('axios')['default']>
    readonly forEach: UnwrapRef<typeof import('lodash-es')['forEach']>
    readonly isPlainObject: UnwrapRef<
      typeof import('lodash-es')['isPlainObject']
    >
    readonly merge: UnwrapRef<typeof import('lodash-es')['merge']>
    readonly remove: UnwrapRef<typeof import('lodash-es')['remove']>
    readonly throttle: UnwrapRef<typeof import('lodash-es')['throttle']>
  }
}
